### ISSUE TITLE
我认为我们应该给n9使用BFS

### ISSUE THREAD

**Issue by shminer** [xiaolvmu/flounder-kernel#1]
没想到可以在这里碰到中国同胞，我之后将合并Zen修改后的bfs源码。
https://github.com/bbedward/ZenKernel_Shamu/blob/master/kernel/sched/bfs.c

**Comment by xiaolvmu** [comment]
https://github.com/zen-kernel/zen-kernel/commits/4.1/bfs/kernel/sched/bfs.c
或许可以从这里backport一下，我放假了就试一试，bfs 这种 process scheduler 挺有趣的

**Comment by shminer** [comment]
我给LG-f460移植了bfs，少了许多特性，比如高通cpuboost的sync freq基于cgroup的一个方法失效。
但是机器性能和相应明显感觉提高了一个层级。

如果想移植原生的bfs，我们可以用这个http://ck.kolivas.org/patches/
